pipeline {
    agent {
        docker {
            image 'node:16-alpine'
            args '-u root:root' // Optional: if you need root access
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node --version'
            }
        }
        stage('Test') {
            steps {
                sh 'npm --version'
            }
        }
    }
}
